### ISSUE TITLE
Support `io.BytesIO` as input

### ISSUE THREAD

**Issue by jams2** [h2non/filetype.py#140]
Hi,

would you be open to a pull request adding support for `io.BytesIO` as input? We use `BytesIO` to ease creating file-like objects for images in testing, but this is incompatible with `filetype` (`TypeError: Unsupported type as file input: <class '_io.BytesIO'>`), as there is no corresponding handling in `utils.get_bytes`.

Thanks

**Comment by ferstar** [comment]
@jams2 I have fix this in [fix: restore reader position after retrieving signature bytes](https://github.com/h2non/filetype.py/commit/bb8fe4cd3b147f4c88ec29bd6662c8995c3dc854)

But it seems we need @h2non to push the latest code to [pypi](https://pypi.org/project/filetype/#history)

**Comment by jams2** [comment]
@ferstar that's great, thanks. Looking forward to the release.

**Comment by pooriazmn** [comment]
Hi @jams2,
Although this [fix](https://github.com/h2non/filetype.py/commit/bb8fe4cd3b147f4c88ec29bd6662c8995c3dc854) addresses this specific issue, not all file-like objects inherit from `io.BufferedIOBase`; for instance, all file-like objects used in Django.

We have been using this package for a long time to determine uploaded file types, but after upgrading to version 1.1.0, we received the same `TypeError`. As a workaround, we just read the first 262 bytes and pass them to the `guess` function and after the new version is released, we can just pass the underlying file object. However, it will be just a specific workaround for django.

Can I ask about the reasoning behind this [commit](https://github.com/h2non/filetype.py/commit/a66c584e4da67f55faa029a9dcbc45f9b323ae21)? Since the try clause didn't seek to the start position, I can see that it could introduce unexpected side-effects, but isn't it more useful to check if the object has `read`, `tell`, and `seek` attributes?

Thanks

**Comment by ferstar** [comment]
@pooriazmn Thanks for pointing this out. Attribute judgment for `read/seek/tell` should be a better choice to be compatible with more object types. I have fixed it.

**Comment by hugo-azevedo** [comment]
Hi @ferstar and @h2non 
Any idea when we can expect a release to pypi of this fix?
Many thanks

**Comment by hugo-azevedo** [comment]
Thanks for pushing it into PyPI, @h2non ! It works perfectly. Cheers
