### ISSUE TITLE
Why the original file has to be broken in get_bytes(obj)?

### ISSUE THREAD

**Issue by abest2016** [h2non/filetype.py#37]
Here → `obj = obj.read(_NUM_SIGNATURE_BYTES)`

If I check my object type like `if filetype.guess_mime(file) != "image/jpeg":`, the file itself will be broken and I can't use it later.

I wonder if it is something intentioned or not.

Thank you!

**Comment by h2non** [comment]
Typically, this happens when the provided input object implements a stream. Data stream implementations will not buffer the whole underlying data per design fundamental principal, otherwise, you should not use a stream, but a memory buffer instead. Streams will flush buffered data after reading it, so you be won't be able to re-read the same stream object again.  

I see two easy solutions here:

1. Recreate a new stream object from scratch, for instance, reading from a file disk again.
2. Use a different data processing structure, such as a buffer itself, reading the needed bytes headers.

**Comment by abest2016** [comment]
Thank you for your time!

I noticed my misunderstanding of stream...

I changed my structure and that works well now.
